apiVersion: v1
kind: Namespace
metadata:
  name: my-keycloak-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-keycloak-operator
spec:
  targetNamespaces:
  - my-keycloak-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-keycloak-operator
  namespace: my-keycloak-operator
spec:
  channel: fast
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
